### ISSUE TITLE
Use Ansible authorized_key module

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/sb-debian-base#49]
Looks like Ansible already provides out of the box a module to add/remove [authorized SSH keys](http://docs.ansible.com/ansible/authorized_key_module.html). The module provided by Ansible seems to be a little bit more flexible than the current approach we are using. Currently we read the content of `keys/<file>` add dump into `/home/<user>/.ssh/authorized_keys`. However, the module provided by Ansible support fetch the public keys from URLs like GitHub.

```YAML
- name: Set authorized key took from url
  authorized_key:
    user: charlie
    state: present
    key: https://github.com/charlie.keys
```

## References
- http://docs.ansible.com/ansible/authorized_key_module.html
